export const theme = {
  colors: {
    BASE_COLOR_DARK: '#231F21',
    BASE_COLOR_LIGHT: '#FFFFFF',
    LIST_WRAP_COLOR: '#2B292A',
    POINT_COLOR: '#F35174',
    BORDER_COLOR: '#555555',
    TEXT_WHITE_COLOR: '#FFFFFF',
    TEXT_DESCRIPTION_COLOR: '#A1A1A1',
    TEXT_INPUT_COLOR: '#AAAAAA',
    TERMS_WRAP_COLOR: '#1c1c1c',
  },
};
